blueprint:
  name: Single button dim switch
  description: Switch a light on/off by pressing a button. Dim it up/down (depending
    on it's current state) by holding the same button.
  domain: automation
  input:
    button:
      name: Push button
      description: Entity representing a physical push button (which restores its
        position when released). It must emit a square signal on press. This automation
        is triggered by its falling edge.
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    light:
      name: Light
      selector:
        entity:
          domain:
          - light
          multiple: false
    hold_threshold:
      name: Hold threshold
      description: Time to consider button is being held, instead of just pushed.
      default: '0.8'
      selector:
        number:
          min: 0.05
          max: 10.0
          step: 0.05
          unit_of_measurement: s
          mode: slider
    brightness_change_speed:
      name: Brightness full span time
      description: Seconds for brightness increase/decrease to go from 0 to 100.
      default: 4.0
      selector:
        number:
          min: 1.0
          max: 10.0
          unit_of_measurement: 's'
          mode: slider
          step: 0.1
  source_url: https://github.com/HairingX/homeassistant/blob/main/blueprints/single-button-on-off-dim-switch.yaml
mode: single
trigger:
- platform: state
  entity_id: !input button
  to: 'on'
action:
- variables:
    entity_id: !input light
    initial_brightness: '{{ state_attr(entity_id, "brightness") | float(0) }}'
    brightness_change_speed: !input brightness_change_speed
    brightness_direction: '{{ -1 if initial_brightness > 130 else 1 }}'
    brightness_target_value: '{{ 0 if brightness_direction < 0 else 255 }}'
    brightness_change_diff: '{{ (brightness_target_value - initial_brightness) | abs }}' 
    brightness_change_time: '{{ brightness_change_speed / 255 * brightness_change_diff }}' 
    brightness_step_pct: '{{ 10 * 2.55 }}'
    brightness_step_pct_negative: '{{ brightness_step_pct * -1 }}'
- wait_for_trigger:
  - platform: state
    entity_id: !input button
    to: 'off'
    from: 'on'
  timeout: !input hold_threshold
  continue_on_timeout: true
- choose:
  - conditions:
    - condition: template
      value_template: '{{ wait.trigger == none }}'
    sequence:
      - service: light.turn_on
        entity_id: !input light
        data:
          transition: '{{ brightness_change_time }}'
          brightness: '{{ brightness_target_value }}'
      - wait_for_trigger:
        - platform: state
          entity_id: !input button
          to: 'off'
        timeout: '{{ brightness_change_time }}'
        continue_on_timeout: true
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ wait.remaining > 0 }}'
          sequence:
          - service: system_log.write
            data:
              level: info
              message: '{{ initial_brightness }}'
          - service: system_log.write
            data:
              level: info
              message: '{{ brightness_change_time }}'
          - service: system_log.write
            data:
              level: info
              message: '{{ wait.remaining }}'
          - service: light.turn_on
            entity_id: !input light
            data:
              transition: 0
              brightness: '{{ initial_brightness + (255 / brightness_change_speed) * (brightness_change_time - wait.remaining) * brightness_direction }}'
  default:
  - service: light.toggle
    entity_id: !input light
